In [2]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int64')

In [4]:
a.ndim

1

In [5]:
a.size

3

In [6]:
a.shape

(3,)

In [8]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])
b

array([[ 1.3,  2.4],
       [ 0.3,  4.1]])

In [9]:
b.ndim

2

In [10]:
b.size

4

In [11]:
b.shape

(2, 2)

In [12]:
b.itemsize

8

In [13]:
b.data

## Types of Data

In [17]:
s = np.array([['a', 'b'],['c','d']])
s

array([['a', 'b'],
       ['c', 'd']], 
      dtype='<U1')

In [18]:
s.dtype.name

'str32'

In [19]:
f = np.array([[1,2,3],[4,5,6]], dtype=complex)
f

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j]])

## Intrinsic Creation of an Array

In [20]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [21]:
np.zeros([3,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(0, 12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [25]:
np.random.random((3,3))

array([[ 0.79841124,  0.83152138,  0.87740978],
       [ 0.74864809,  0.4788172 ,  0.44174077],
       [ 0.55886194,  0.37399601,  0.33277593]])

## Basic Operations

In [26]:
a+1

array([2, 3, 4])

In [27]:
a*2

array([2, 4, 6])

In [29]:
(a + 1) * a

array([ 2,  6, 12])

In [30]:
(a + 1) - a

array([1, 1, 1])

In [31]:
a * np.sin(a)

array([ 0.84147098,  1.81859485,  0.42336002])

In [32]:
np.sqrt(a)

array([ 1.        ,  1.41421356,  1.73205081])

In [3]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b = a + 2
b

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
a.dot(b)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

In [6]:
np.dot(a,b)

array([[ 42,  48,  54],
       [ 96, 111, 126],
       [150, 174, 198]])

## Aggregate Functions

In [41]:
print(a.sum())
print(a.min())
print(a.max())

45
1
9


In [42]:
a.mean()

5.0

In [43]:
a.std()

2.5819888974716112

## Indexing, Slicing and Iterating

In [45]:
a[1,1]

5

In [47]:
a[1,:]

array([4, 5, 6])

In [48]:
a[:,1]

array([2, 5, 8])

In [49]:
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [50]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [51]:
for i in a.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [52]:
np.apply_along_axis(np.mean, axis=0, arr=a)

array([ 4.,  5.,  6.])

In [53]:
np.apply_along_axis(np.mean, axis=1, arr=a)

array([ 2.,  5.,  8.])

In [60]:
def foo(x):
    print(x)
    return np.mean(x)

np.apply_along_axis(foo, axis=1, arr=a)

[1 2 3]
[4 5 6]
[7 8 9]


array([ 2.,  5.,  8.])

## Conditions and Boolean Arrays

In [61]:
a < 5

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]], dtype=bool)

In [62]:
a[a<5]

array([1, 2, 3, 4])

In [63]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Array Manipulation

In [67]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [68]:
np.hstack((a,b))

array([[ 1,  2,  3,  3,  4,  5],
       [ 4,  5,  6,  6,  7,  8],
       [ 7,  8,  9,  9, 10, 11]])

In [70]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [72]:
np.row_stack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [73]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
[b,c] = np.hsplit(a,2)
b

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [76]:
c

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [77]:
[b,c] = np.vsplit(a,2)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
c

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
v,a1 = np.split(a, [1], axis=1)
v

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [84]:
a1

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [85]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Loading and Saving Data

In [87]:
np.save("saved4x4",a)

In [88]:
a2 = np.load("saved4x4.npy")
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
data = np.genfromtxt("partitions.csv",delimiter=',',names=True)
data

array([(10.0, 1.0, 2.0, 100.0, 8192.0), (20.0, 1.0, 2.0, 200.0, 16384.0),
       (30.0, 1.0, 2.0, 300.0, 32768.0), (40.0, 2.0, 3.0, 400.0, 65536.0)], 
      dtype=[('Name', '<f8'), ('Type', '<f8'), ('SubType', '<f8'), ('Offset', '<f8'), ('Size', '<f8')])